# Generated by Django 5.1.6 on 2025-08-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('self_employed', models.CharField(max_length=5)),
                ('family_history', models.CharField(max_length=5)),
                ('work_interfere', models.CharField(max_length=20)),
                ('no_employees', models.CharField(max_length=20)),
                ('remote_work', models.CharField(max_length=5)),
                ('prediction_result', models.CharField(max_length=5)),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
